-- MySQL Script generated by MySQL Workbench
-- 07/07/14 00:19:19
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alumnos` ;

CREATE TABLE IF NOT EXISTS `Alumnos` (
  `idAlumnos` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(60) NULL,
  `Apellido` VARCHAR(60) NULL,
  `FechaNacimiento` DATETIME NULL,
  PRIMARY KEY (`idAlumnos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Curso` ;

CREATE TABLE IF NOT EXISTS `Curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `Curso` VARCHAR(50) NULL,
  `Creditos` VARCHAR(45) NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Asignacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Asignacion` ;

CREATE TABLE IF NOT EXISTS `Asignacion` (
  `idAsignacion` INT NOT NULL AUTO_INCREMENT,
  `Curso_idCurso` INT NOT NULL,
  `Alumnos_idAlumnos` INT NOT NULL,
  `Fecha` DATETIME NULL,
  PRIMARY KEY (`idAsignacion`),
  INDEX `fk_Asignacion_Curso_idx` (`Curso_idCurso` ASC),
  INDEX `fk_Asignacion_Alumnos1_idx` (`Alumnos_idAlumnos` ASC),
  CONSTRAINT `fk_Asignacion_Curso`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignacion_Alumnos1`
    FOREIGN KEY (`Alumnos_idAlumnos`)
    REFERENCES `Alumnos` (`idAlumnos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
