//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualizacionApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualizacionApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Babb
        ///Babar
        ///Badilla
        ///Bado
        ///Báez
        ///Baeza
        ///Baidal
        ///Bairnales
        ///Baizan
        ///Bajarano
        ///Balarezo
        ///Baldares
        ///Balderas
        ///Balderrama
        ///Balderramos
        ///Balladares
        ///Ballar 
        ///Ballard
        ///Ballestero
        ///Balmaños
        ///Amado
        ///Amador
        ///Amalla
        ///Amaris
        ///Amaya
        ///Amor
        ///Amora
        ///Amores
        ///Amoros
        ///Ampie
        ///Ampié
        ///Ampiée
        ///Ampiee
        ///Anaya
        ///Anchez
        ///Anchía
        ///Anchieta
        ///Andia
        ///Andino
        ///Andrade
        ///André
        ///Andrés
        ///Angele
        ///Angelini
        ///Anglada
        ///Angulo
        ///Anice
        ///Anjos
        ///Ansorena
        ///Antelo
        ///Lainez
        ///Laitano
        ///Lamas
        ///Lamuza
        ///Lancho
        ///Landazuri
        ///Lández
        ///Lanuza
        ///Lanza
        ///Lanzas
        ///Lapeira
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string apellidos {
            get {
                return ResourceManager.GetString("apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALCULO I
        ///CALCULO II
        ///CALCULO III
        ///FISICA I
        ///FISICA II
        ///FISICA III
        ///ECUACIONES DIFERENCIALES
        ///INTRODUCCION A LA PROGRAMACION
        ///PROGRAMACION AVANZADA
        ///ESTRUCTURA DE DATOS I
        ///ESTRUCTURA DE DATOS II
        ///BASE DE DATOS I
        ///BASE DE DATOS II
        ///ARQUITECTURA DEL COMPUTADOR I
        ///ARQUITECTURA DEL COMPUTADOR II
        ///SISTEMAS OPERATIVOS I
        ///SISTEMAS OPERATIVOS II
        ///MICROPROGRAMACION
        ///ORGANIZACION COMPUTACIONAL
        ///QUIMICA I
        ///QUIMICA II
        ///QUIMICA III
        ///REDES I
        ///REDES II
        ///COMPILADORES
        ///ELECTROMAGNETISMO
        ///INVESTIGACION DE OPERACIONES I
        ///INV [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cursos {
            get {
                return ResourceManager.GetString("cursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isabella
        ///Olivia
        ///Alexis
        ///Sofía
        ///Victoria
        ///Amelia
        ///Alexa
        ///Julia
        ///Camila
        ///Alexandra
        ///Maya
        ///Andrea
        ///Ariana
        ///María
        ///Eva
        ///Angelina
        ///Valeria
        ///Natalia
        ///Isabel
        ///Sara
        ///Liliana
        ///Adriana
        ///Juliana
        ///Gabriela
        ///Daniela
        ///Valentina
        ///Lila
        ///Vivian
        ///Nora
        ///Ángela
        ///Elena
        ///Clara
        ///Eliana
        ///Alana
        ///Miranda
        ///Amanda
        ///Diana
        ///Ana
        ///Penélope
        ///Aurora
        ///Alexandría
        ///Lola
        ///Alicia
        ///Amaya
        ///Alexia
        ///Jazmín
        ///Mariana
        ///Alina
        ///Lucía
        ///Fátima
        ///Ximena
        ///Laura
        ///Cecilia
        ///Alejandra
        ///Esmeralda
        ///Verónica
        ///Daniella
        ///Miriam
        ///Carmen
        ///Iris
        ///Guadalupe
        ///Selena
        ///Fern [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nombres {
            get {
                return ResourceManager.GetString("nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localhost
        ///root
        ///Mysql123.
        ///dbcursos.
        /// </summary>
        public static string server {
            get {
                return ResourceManager.GetString("server", resourceCulture);
            }
            set
            {
            }
        }
    }
}
